name: Github Action for LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: print path
      run: echo you're in ${{./*/*.tex}}
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ../../*/*.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with: 
        name: PDF
        path: ./*/*.pdf
